### ISSUE TITLE
Confusion about audio2lm/test.py

### ISSUE THREAD

**Issue by zizizihua** [jixinya/EVP#23]
audio2lm/test.py#L113
`example_landmark  = example_landmark - mean.expand_as(example_landmark)`

Both `example_landmark` and `mean` are loaded from `config['mean']`, which will output 0?

**Comment by jixinya** [comment]
Hi, we are trying to predict the landmark motion displacement for the example_landmark in test.py, so that we can set the example_landmark with different identities or mouth shapes. If the example_landmark is mean, which is the case in test.py, the input for the encoder will be 0.
