### ISSUE TITLE
No such file or directory: base_weight.pickle

### ISSUE THREAD

**Issue by jeesunkim** [jixinya/EVP#4]
Enjoyed the paper - thanks! Looking forward to seeing the training code :)  -
A few things:
1. in test.py line 208 add_audio(config['video_dir'], opt.in_file) throws an error - AttributeError: 'Namespace' object has no attribute 'in_file' (the coide runs if this line is commented out).
2. Line 3 in M003_test.yaml video_dir: audio2lm/result/M003.mp4 throws an error - OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)' that can be fixed by changing it to video_dir: audio2lm/result/M003.avi
3. In section 2 - running python lm2video/lm2map.py results in FileNotFoundError: [Errno 2] No such file or directory: './base_weight.pickle' - not sure how this file is generated or obtained.
Any help much appreciated - 谢谢你

**Comment by jixinya** [comment]
Thanks for your notice. The code has been updated and we change the 'opt.in_file'  into 'opt.audio' in test.py line 208. And 'base_weight.pickle'  can be found in [google-drive](https://drive.google.com/file/d/1QQeE8ahQC_ErPBzTc6Kx5pzOAWcRoNs4/view) under the path '/lm2video/base_weight.pickle' in README.md.

**Comment by jeesunkim** [comment]
Great - that works - so, closing this issue 👍
