### ISSUE TITLE
About the landmark MEAN and PCA 

### ISSUE THREAD

**Issue by DaddyJin** [jixinya/EVP#5]
Thank you for the great work.
Could you please share the detail of calculating one specific person's landmark mean and pca?
Take a specific person's video data in MEAD for example. We have multiple viewpoints, emotions and intensities. Could you please tell which videos are used to calculate the landmark and produce mean and pca? Like front view with intensity 3? or front view with intensity 2? or some other combination or even all the videos.

I am trying to pre-process the MEAD dataset and do some face reenactment work, I would appreciate it a lot if you may share the pre-processing details. 
Looking forward to the reply!

**Comment by jixinya** [comment]
We use the front view with intensity 3 to calculate the landmark and we will share the pre-processing details soon.

**Comment by DaddyJin** [comment]
Thank you for the reply and looking forward to the pre-processing details.

**Comment by zhanghm1995** [comment]
> We use the front view with intensity 3 to calculate the landmark and we will share the pre-processing details soon.

Hi, @jixinya , have you cleaned up your pre-processing code now? I'm also interested in the Mean and PCA computation pipeline.
